echo "============================================================"
echo "                PHOENIX SYNC ALL DIAGNOSTICS"
echo "============================================================"
echo ""

# --- DNS Diagnostics ---
echo "--- 1. DNS Resolution & Configuration ---"
echo "[INFO] Hypervisor /etc/resolv.conf:"
cat /etc/resolv.conf
echo ""
echo "[INFO] Dnsmasq internal records configuration:"
cat /etc/dnsmasq.d/00-phoenix-internal.conf 2>/dev/null || echo "File not found."
echo ""
echo "[INFO] Dnsmasq service status:"
systemctl status dnsmasq --no-pager 2>/dev/null || echo "Service not running or found."
echo ""
echo "[INFO] Performing DNS lookup for portainer.internal.thinkheads.ai from hypervisor:"
dig portainer.internal.thinkheads.ai @127.0.0.1 || echo "Dig command failed."
echo ""

# --- Firewall Diagnostics ---
echo "--- 2. Firewall Status & Rules ---"
echo "[INFO] Proxmox Firewall Service Status:"
pve-firewall status || echo "Command failed."
echo ""
echo "[INFO] Cluster Firewall Rules (/etc/pve/firewall/cluster.fw):"
cat /etc/pve/firewall/cluster.fw 2>/dev/null || echo "File not found."
echo ""
echo "[INFO] Hypervisor Firewall Rules (/etc/pve/firewall/<node_name>.fw):"
cat /etc/pve/firewall/$(hostname).fw 2>/dev/null || echo "File not found."
echo ""
echo "[INFO] Nginx (101) Firewall Rules (/etc/pve/firewall/101.fw):"
cat /etc/pve/firewall/101.fw 2>/dev/null || echo "File not found."
echo ""
echo "[INFO] Traefik (102) Firewall Rules (/etc/pve/firewall/102.fw):"
cat /etc/pve/firewall/102.fw 2>/dev/null || echo "File not found."
echo ""
echo "[INFO] Portainer (1001) Firewall Rules (/etc/pve/firewall/1001.fw):"
cat /etc/pve/firewall/1001.fw 2>/dev/null || echo "File not found."
echo ""

# --- Connectivity Test ---
echo "--- 4. End-to-End Connectivity Test ---"
echo "[INFO] Testing connection from Hypervisor to Portainer via Nginx gateway..."
echo "[CMD] curl -v --cacert /usr/local/share/ca-certificates/phoenix_internal_root_ca.crt https://portainer.internal.thinkheads.ai/api/status"
curl -v --cacert /usr/local/share/ca-certificates/phoenix_internal_root_ca.crt https://portainer.internal.thinkheads.ai/api/status || echo "Curl command failed."
echo ""

echo "============================================================"
echo "                      DIAGNOSTICS COMPLETE"
echo "============================================================"
EOF