version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /var/lib/docker/volumes/qdrant_storage/_data:/qdrant/storage:z